### ISSUE TITLE
您好，表格识别模型ch_ppstructure_mobile_v2.0_SLANet_infer.onnx在openvino下识别结果跟paddleocr原模型存在误差，您那有碰到过吗

### ISSUE THREAD

**Issue by cdycdycdy** [OpenVINO-dev-contest/PaddleOCR_OpenVINO_CPP#1]
您好，表格识别模型ch_ppstructure_mobile_v2.0_SLANet_infer.onnx在openvino2022下识别结果跟paddleocr原模型存在误差，您那有碰到过吗

**Comment by openvino-dev-samples** [comment]
是的，目前这个有些问题，你可以尝试en_ppocr_mobile_v2.0_table_structure

**Comment by cdycdycdy** [comment]
存在整体值偏差，但是误差不大，小数点后几位，但影响最终结果。en_ppocr_mobile_v2.0_table_structure这个模型对中文表格识别效果如何呢

**Comment by openvino-dev-samples** [comment]
这个目前我还没有测试，你有兴趣的话，可以试一下

**Comment by cdycdycdy** [comment]
> 这个目前我还没有测试，你有兴趣的话，可以试一下

我试了哈，他跟中文表格模型是一样的结构，存在同样的问题，识别结果不好

**Comment by openvino-dev-samples** [comment]
是那个6.8MB的模型吗，模型结构应该不一样吧

**Comment by cdycdycdy** [comment]
> 是那个6.8MB的模型吗，模型结构应该不一样吧

这个模型，官方人员回复说目前不支持：https://github.com/PaddlePaddle/PaddleOCR/issues/7472

**Comment by openvino-dev-samples** [comment]
我试过可以转onnx，也可以跑这个示例

**Comment by cdycdycdy** [comment]
> 我试过可以转onnx，也可以跑这个示例

那这个效果有好些吗

**Comment by openvino-dev-samples** [comment]
没有测试过中文表格和文档

**Comment by cdycdycdy** [comment]
> 没有测试过中文表格和文档

6.8M,python测了下中文文档，效果不好哈

**Comment by openvino-dev-samples** [comment]
模型适配上的问题，您这边如果有具体项目需求，我可以协调资源开发。

**Comment by cdycdycdy** [comment]
> 模型适配上的问题，您这边如果有具体项目需求，我可以协调资源开发。

纯属个人爱好哈，谢谢您。我这边还有个问题想请教下，表格识别模型ch_ppstructure_mobile_v2.0_SLANet_infer转onnx时，会显示很多层名需要rename问题
(paddle_env) H:\PaddleOcr\ppocrv3_mnn\PaddleDemo\x64\Release\models>paddle2onnx --model_dir ./ch_ppstructure_mobile_v2.0_SLANet_infer --model_filename inference.pdmodel --params_filename inference.pdiparams --save_file ch_ppstructure_m
obile_v2.0_SLANet_infer.onnx --enable_dev_version True --opset_version 13 --enable_onnx_checker True
[Paddle2ONNX] Start to parse PaddlePaddle model...
[Paddle2ONNX] Model file path: ./ch_ppstructure_mobile_v2.0_SLANet_infer\inference.pdmodel
[Paddle2ONNX] Paramters file path: ./ch_ppstructure_mobile_v2.0_SLANet_infer\inference.pdiparams
[Paddle2ONNX] Start to parsing Paddle model...
[Paddle2ONNX] Detected there's control flow 'while' op in your model, this requires the minimal opset version of 13.
[Paddle2ONNX] Use opset_version = 13 for ONNX export.
[Paddle2ONNX] Find dumplicate output name 'fill_constant_9.tmp_0', it will rename to 'p2o.fill_constant_9.tmp_0.0'.
[Paddle2ONNX] Find dumplicate output name 'fill_constant_15.tmp_0', it will rename to 'p2o.fill_constant_15.tmp_0.0'.
[Paddle2ONNX] Find dumplicate output name 'fill_constant_21.tmp_0', it will rename to 'p2o.fill_constant_21.tmp_0.0'.
[Paddle2ONNX] Find dumplicate output name 'p2o.fill_constant_15.tmp_0.0', it will rename to 'p2o.p2o.fill_constant_15.tmp_0.0.0'.
[Paddle2ONNX] Find dumplicate output name 'fill_constant_5.tmp_0', it will rename to 'p2o.fill_constant_5.tmp_0.0'.
[Paddle2ONNX] Find dumplicate output name 'fill_constant_23.tmp_0', it will rename to 'p2o.fill_constant_23.tmp_0.0'.
[Paddle2ONNX] Find dumplicate output name 'p2o.fill_constant_9.tmp_0.0', it will rename to 'p2o.p2o.fill_constant_9.tmp_0.0.0'.
[Paddle2ONNX] Find dumplicate output name 'assign_0.tmp_0', it will rename to 'p2o.assign_0.tmp_0.0'.
[Paddle2ONNX] Find dumplicate output name 'transpose_0.tmp_0', it will rename to 'p2o.transpose_0.tmp_0.0'.
[Paddle2ONNX] Find dumplicate output name 'tmp_4', it will rename to 'p2o.tmp_4.0'.
[Paddle2ONNX] Find dumplicate output name 'linear_1.b_0', it will rename to 'p2o.linear_1.b_0.0'.
[Paddle2ONNX] Find dumplicate output name 'gru_cell_0.w_1', it will rename to 'p2o.gru_cell_0.w_1.0'.
[Paddle2ONNX] Find dumplicate output name 'linear_3.b_0', it will rename to 'p2o.linear_3.b_0.0'.
[Paddle2ONNX] Find dumplicate output name 'linear_1.w_0', it will rename to 'p2o.linear_1.w_0.0'.
[Paddle2ONNX] Find dumplicate output name 'linear_0.w_0', it will rename to 'p2o.linear_0.w_0.0'.
[Paddle2ONNX] Find dumplicate output name 'linear_5.b_0', it will rename to 'p2o.linear_5.b_0.0'.
[Paddle2ONNX] Find dumplicate output name 'fill_constant_9.tmp_0', it will rename to 'p2o.fill_constant_9.tmp_0.1'.
[Paddle2ONNX] Find dumplicate output name 'fill_constant_23.tmp_0', it will rename to 'p2o.fill_constant_23.tmp_0.1'.
[Paddle2ONNX] Find dumplicate output name 'assign_0.tmp_0', it will rename to 'p2o.assign_0.tmp_0.1'.
[Paddle2ONNX] Find dumplicate output name 'linear_5.w_0', it will rename to 'p2o.linear_5.w_0.0'.
[Paddle2ONNX] Find dumplicate output name 'fill_constant_15.tmp_0', it will rename to 'p2o.fill_constant_15.tmp_0.1'.
[Paddle2ONNX] Find dumplicate output name 'gru_cell_0.b_0', it will rename to 'p2o.gru_cell_0.b_0.0'.
[Paddle2ONNX] Find dumplicate output name 'fill_constant_5.tmp_0', it will rename to 'p2o.fill_constant_5.tmp_0.1'.
[Paddle2ONNX] Find dumplicate output name 'linear_2.w_0', it will rename to 'p2o.linear_2.w_0.0'.
[Paddle2ONNX] Find dumplicate output name 'linear_4.w_0', it will rename to 'p2o.linear_4.w_0.0'.
[Paddle2ONNX] Find dumplicate output name 'linear_6.w_0', it will rename to 'p2o.linear_6.w_0.0'.
[Paddle2ONNX] Find dumplicate output name 'gru_cell_0.w_0', it will rename to 'p2o.gru_cell_0.w_0.0'.
[Paddle2ONNX] Find dumplicate output name 'gru_cell_0.b_1', it will rename to 'p2o.gru_cell_0.b_1.0'.
[Paddle2ONNX] Find dumplicate output name 'fill_constant_21.tmp_0', it will rename to 'p2o.fill_constant_21.tmp_0.1'.
[Paddle2ONNX] Find dumplicate output name 'linear_3.w_0', it will rename to 'p2o.linear_3.w_0.0'.
[Paddle2ONNX] Find dumplicate output name 'transpose_0.tmp_0', it will rename to 'p2o.transpose_0.tmp_0.1'.
[Paddle2ONNX] Find dumplicate output name 'linear_6.b_0', it will rename to 'p2o.linear_6.b_0.0'.
[Paddle2ONNX] Find dumplicate output name 'linear_4.b_0', it will rename to 'p2o.linear_4.b_0.0'.
[Paddle2ONNX] PaddlePaddle model is exported as ONNX format now.
2023-03-07 13:45:25 [INFO] ===============Make PaddlePaddle Better!================
2023-03-07 13:45:25 [INFO] A little survey: https://iwenjuan.baidu.com/?code=r8hu2s
您那有遇到过吗？

**Comment by openvino-dev-samples** [comment]
抱歉，我对paddle2onnx不太熟悉，你可否在P2O的仓库里咨询一下？

**Comment by cdycdycdy** [comment]
> 抱歉，我对paddle2onnx不太熟悉，你可否在P2O的仓库里咨询一下？

好的 谢谢您
