### ISSUE TITLE
执行到以下代码时报错: Recognizer::Run() -> this->infer_request.infer()

### ISSUE THREAD

**Issue by yao-xiaofei** [OpenVINO-dev-contest/PaddleOCR_OpenVINO_CPP#3]
非常感谢作者贡献此项目供我们学习！

系统环境：win11 / VS 2022 Professional
版本号：Paddle： PaddleOCR-2.6.0 /  OpenVINO:  2022.3.0
识别模型：ch_PP-OCRv3_rec_infer

我在VS2022环境下推理时发生以下异常:：

Microsoft Visual C++ Runtime Library
Debug Assertion Failed!

Program: ...dows\runtime\bin\intel64\Debug\openvino_intel_cpu_plugind.dll
File: C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.28.29333\include\vector
Line: 1501

Expression: vector subscript out of range

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts.

(Press Retry to debug the application)

**Comment by yao-xiaofei** [comment]
OpenVINO Runtime版本升级到2023.0后,不再报异常

**Comment by openvino-dev-samples** [comment]
谢谢告知，之前还没来得及测
